/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OfficerSosRouteImport } from './routes/officer.sos'
import { Route as OfficerScheduleRouteImport } from './routes/officer.schedule'
import { Route as OfficerPatrolRouteImport } from './routes/officer.patrol'
import { Route as OfficerNotificationsRouteImport } from './routes/officer.notifications'
import { Route as OfficerNavigationRouteImport } from './routes/officer.navigation'
import { Route as OfficerHomeRouteImport } from './routes/officer.home'
import { Route as OfficerDispatchRouteImport } from './routes/officer.dispatch'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReportCentreRouteImport } from './routes/app.report-centre'
import { Route as AppPatrolsRouteImport } from './routes/app.patrols'
import { Route as AppOrgRouteImport } from './routes/app.org'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppLocationsRouteImport } from './routes/app.locations'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppIntelligenceRouteImport } from './routes/app.intelligence'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as OfficerIncidentNewRouteImport } from './routes/officer.incident.new'
import { Route as OfficerIncidentIdRouteImport } from './routes/officer.incident.$id'
import { Route as AppUsersIdRouteImport } from './routes/app.users.$id'
import { Route as AppPatrolsIdRouteImport } from './routes/app.patrols.$id'
import { Route as AppIncidentsIdRouteImport } from './routes/app.incidents.$id'
import { Route as AppAdminSystemRouteImport } from './routes/app.admin.system'
import { Route as AppAdminOrganisationsRouteImport } from './routes/app.admin.organisations'
import { Route as AppAdminBillingRouteImport } from './routes/app.admin.billing'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminOrganisationsIdRouteImport } from './routes/app.admin.organisations.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OfficerSosRoute = OfficerSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerScheduleRoute = OfficerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerPatrolRoute = OfficerPatrolRouteImport.update({
  id: '/patrol',
  path: '/patrol',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerNotificationsRoute = OfficerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerNavigationRoute = OfficerNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerHomeRoute = OfficerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDispatchRoute = OfficerDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => OfficerRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReportCentreRoute = AppReportCentreRouteImport.update({
  id: '/report-centre',
  path: '/report-centre',
  getParentRoute: () => AppRoute,
} as any)
const AppPatrolsRoute = AppPatrolsRouteImport.update({
  id: '/patrols',
  path: '/patrols',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const OfficerIncidentNewRoute = OfficerIncidentNewRouteImport.update({
  id: '/incident/new',
  path: '/incident/new',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerIncidentIdRoute = OfficerIncidentIdRouteImport.update({
  id: '/incident/$id',
  path: '/incident/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppPatrolsIdRoute = AppPatrolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPatrolsRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIncidentsRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrganisationsRoute = AppAdminOrganisationsRouteImport.update({
  id: '/admin/organisations',
  path: '/admin/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrganisationsIdRoute = AppAdminOrganisationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminOrganisationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/incidents': typeof AppIncidentsRouteWithChildren
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/map': typeof AppMapRoute
  '/app/org': typeof AppOrgRoute
  '/app/patrols': typeof AppPatrolsRouteWithChildren
  '/app/report-centre': typeof AppReportCentreRoute
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/officer/dispatch': typeof OfficerDispatchRoute
  '/officer/home': typeof OfficerHomeRoute
  '/officer/navigation': typeof OfficerNavigationRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/patrol': typeof OfficerPatrolRoute
  '/officer/schedule': typeof OfficerScheduleRoute
  '/officer/sos': typeof OfficerSosRoute
  '/app/': typeof AppIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/organisations': typeof AppAdminOrganisationsRouteWithChildren
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/patrols/$id': typeof AppPatrolsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/officer/incident/$id': typeof OfficerIncidentIdRoute
  '/officer/incident/new': typeof OfficerIncidentNewRoute
  '/app/admin/organisations/$id': typeof AppAdminOrganisationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/incidents': typeof AppIncidentsRouteWithChildren
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/map': typeof AppMapRoute
  '/app/org': typeof AppOrgRoute
  '/app/patrols': typeof AppPatrolsRouteWithChildren
  '/app/report-centre': typeof AppReportCentreRoute
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/officer/dispatch': typeof OfficerDispatchRoute
  '/officer/home': typeof OfficerHomeRoute
  '/officer/navigation': typeof OfficerNavigationRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/patrol': typeof OfficerPatrolRoute
  '/officer/schedule': typeof OfficerScheduleRoute
  '/officer/sos': typeof OfficerSosRoute
  '/app': typeof AppIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/organisations': typeof AppAdminOrganisationsRouteWithChildren
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/patrols/$id': typeof AppPatrolsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/officer/incident/$id': typeof OfficerIncidentIdRoute
  '/officer/incident/new': typeof OfficerIncidentNewRoute
  '/app/admin/organisations/$id': typeof AppAdminOrganisationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/incidents': typeof AppIncidentsRouteWithChildren
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/map': typeof AppMapRoute
  '/app/org': typeof AppOrgRoute
  '/app/patrols': typeof AppPatrolsRouteWithChildren
  '/app/report-centre': typeof AppReportCentreRoute
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/officer/dispatch': typeof OfficerDispatchRoute
  '/officer/home': typeof OfficerHomeRoute
  '/officer/navigation': typeof OfficerNavigationRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/patrol': typeof OfficerPatrolRoute
  '/officer/schedule': typeof OfficerScheduleRoute
  '/officer/sos': typeof OfficerSosRoute
  '/app/': typeof AppIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/organisations': typeof AppAdminOrganisationsRouteWithChildren
  '/app/admin/system': typeof AppAdminSystemRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/patrols/$id': typeof AppPatrolsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/officer/incident/$id': typeof OfficerIncidentIdRoute
  '/officer/incident/new': typeof OfficerIncidentNewRoute
  '/app/admin/organisations/$id': typeof AppAdminOrganisationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/officer'
    | '/onboarding'
    | '/reset-password'
    | '/app/alerts'
    | '/app/audit'
    | '/app/incidents'
    | '/app/intelligence'
    | '/app/inventory'
    | '/app/locations'
    | '/app/map'
    | '/app/org'
    | '/app/patrols'
    | '/app/report-centre'
    | '/app/reports'
    | '/app/users'
    | '/officer/dispatch'
    | '/officer/home'
    | '/officer/navigation'
    | '/officer/notifications'
    | '/officer/patrol'
    | '/officer/schedule'
    | '/officer/sos'
    | '/app/'
    | '/officer/'
    | '/app/admin/audit'
    | '/app/admin/billing'
    | '/app/admin/organisations'
    | '/app/admin/system'
    | '/app/incidents/$id'
    | '/app/patrols/$id'
    | '/app/users/$id'
    | '/officer/incident/$id'
    | '/officer/incident/new'
    | '/app/admin/organisations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/alerts'
    | '/app/audit'
    | '/app/incidents'
    | '/app/intelligence'
    | '/app/inventory'
    | '/app/locations'
    | '/app/map'
    | '/app/org'
    | '/app/patrols'
    | '/app/report-centre'
    | '/app/reports'
    | '/app/users'
    | '/officer/dispatch'
    | '/officer/home'
    | '/officer/navigation'
    | '/officer/notifications'
    | '/officer/patrol'
    | '/officer/schedule'
    | '/officer/sos'
    | '/app'
    | '/officer'
    | '/app/admin/audit'
    | '/app/admin/billing'
    | '/app/admin/organisations'
    | '/app/admin/system'
    | '/app/incidents/$id'
    | '/app/patrols/$id'
    | '/app/users/$id'
    | '/officer/incident/$id'
    | '/officer/incident/new'
    | '/app/admin/organisations/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/officer'
    | '/onboarding'
    | '/reset-password'
    | '/app/alerts'
    | '/app/audit'
    | '/app/incidents'
    | '/app/intelligence'
    | '/app/inventory'
    | '/app/locations'
    | '/app/map'
    | '/app/org'
    | '/app/patrols'
    | '/app/report-centre'
    | '/app/reports'
    | '/app/users'
    | '/officer/dispatch'
    | '/officer/home'
    | '/officer/navigation'
    | '/officer/notifications'
    | '/officer/patrol'
    | '/officer/schedule'
    | '/officer/sos'
    | '/app/'
    | '/officer/'
    | '/app/admin/audit'
    | '/app/admin/billing'
    | '/app/admin/organisations'
    | '/app/admin/system'
    | '/app/incidents/$id'
    | '/app/patrols/$id'
    | '/app/users/$id'
    | '/officer/incident/$id'
    | '/officer/incident/new'
    | '/app/admin/organisations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/officer/sos': {
      id: '/officer/sos'
      path: '/sos'
      fullPath: '/officer/sos'
      preLoaderRoute: typeof OfficerSosRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/schedule': {
      id: '/officer/schedule'
      path: '/schedule'
      fullPath: '/officer/schedule'
      preLoaderRoute: typeof OfficerScheduleRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/patrol': {
      id: '/officer/patrol'
      path: '/patrol'
      fullPath: '/officer/patrol'
      preLoaderRoute: typeof OfficerPatrolRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/notifications': {
      id: '/officer/notifications'
      path: '/notifications'
      fullPath: '/officer/notifications'
      preLoaderRoute: typeof OfficerNotificationsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/navigation': {
      id: '/officer/navigation'
      path: '/navigation'
      fullPath: '/officer/navigation'
      preLoaderRoute: typeof OfficerNavigationRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/home': {
      id: '/officer/home'
      path: '/home'
      fullPath: '/officer/home'
      preLoaderRoute: typeof OfficerHomeRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dispatch': {
      id: '/officer/dispatch'
      path: '/dispatch'
      fullPath: '/officer/dispatch'
      preLoaderRoute: typeof OfficerDispatchRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report-centre': {
      id: '/app/report-centre'
      path: '/report-centre'
      fullPath: '/app/report-centre'
      preLoaderRoute: typeof AppReportCentreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patrols': {
      id: '/app/patrols'
      path: '/patrols'
      fullPath: '/app/patrols'
      preLoaderRoute: typeof AppPatrolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org': {
      id: '/app/org'
      path: '/org'
      fullPath: '/app/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations': {
      id: '/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intelligence': {
      id: '/app/intelligence'
      path: '/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/officer/incident/new': {
      id: '/officer/incident/new'
      path: '/incident/new'
      fullPath: '/officer/incident/new'
      preLoaderRoute: typeof OfficerIncidentNewRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/incident/$id': {
      id: '/officer/incident/$id'
      path: '/incident/$id'
      fullPath: '/officer/incident/$id'
      preLoaderRoute: typeof OfficerIncidentIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/app/users/$id': {
      id: '/app/users/$id'
      path: '/$id'
      fullPath: '/app/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/patrols/$id': {
      id: '/app/patrols/$id'
      path: '/$id'
      fullPath: '/app/patrols/$id'
      preLoaderRoute: typeof AppPatrolsIdRouteImport
      parentRoute: typeof AppPatrolsRoute
    }
    '/app/incidents/$id': {
      id: '/app/incidents/$id'
      path: '/$id'
      fullPath: '/app/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
    '/app/admin/system': {
      id: '/app/admin/system'
      path: '/admin/system'
      fullPath: '/app/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/organisations': {
      id: '/app/admin/organisations'
      path: '/admin/organisations'
      fullPath: '/app/admin/organisations'
      preLoaderRoute: typeof AppAdminOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/billing': {
      id: '/app/admin/billing'
      path: '/admin/billing'
      fullPath: '/app/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/organisations/$id': {
      id: '/app/admin/organisations/$id'
      path: '/$id'
      fullPath: '/app/admin/organisations/$id'
      preLoaderRoute: typeof AppAdminOrganisationsIdRouteImport
      parentRoute: typeof AppAdminOrganisationsRoute
    }
  }
}

interface AppIncidentsRouteChildren {
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIdRoute: AppIncidentsIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppPatrolsRouteChildren {
  AppPatrolsIdRoute: typeof AppPatrolsIdRoute
}

const AppPatrolsRouteChildren: AppPatrolsRouteChildren = {
  AppPatrolsIdRoute: AppPatrolsIdRoute,
}

const AppPatrolsRouteWithChildren = AppPatrolsRoute._addFileChildren(
  AppPatrolsRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersIdRoute: typeof AppUsersIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersIdRoute: AppUsersIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppAdminOrganisationsRouteChildren {
  AppAdminOrganisationsIdRoute: typeof AppAdminOrganisationsIdRoute
}

const AppAdminOrganisationsRouteChildren: AppAdminOrganisationsRouteChildren = {
  AppAdminOrganisationsIdRoute: AppAdminOrganisationsIdRoute,
}

const AppAdminOrganisationsRouteWithChildren =
  AppAdminOrganisationsRoute._addFileChildren(
    AppAdminOrganisationsRouteChildren,
  )

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMapRoute: typeof AppMapRoute
  AppOrgRoute: typeof AppOrgRoute
  AppPatrolsRoute: typeof AppPatrolsRouteWithChildren
  AppReportCentreRoute: typeof AppReportCentreRoute
  AppReportsRoute: typeof AppReportsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminOrganisationsRoute: typeof AppAdminOrganisationsRouteWithChildren
  AppAdminSystemRoute: typeof AppAdminSystemRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAuditRoute: AppAuditRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMapRoute: AppMapRoute,
  AppOrgRoute: AppOrgRoute,
  AppPatrolsRoute: AppPatrolsRouteWithChildren,
  AppReportCentreRoute: AppReportCentreRoute,
  AppReportsRoute: AppReportsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminOrganisationsRoute: AppAdminOrganisationsRouteWithChildren,
  AppAdminSystemRoute: AppAdminSystemRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OfficerRouteChildren {
  OfficerDispatchRoute: typeof OfficerDispatchRoute
  OfficerHomeRoute: typeof OfficerHomeRoute
  OfficerNavigationRoute: typeof OfficerNavigationRoute
  OfficerNotificationsRoute: typeof OfficerNotificationsRoute
  OfficerPatrolRoute: typeof OfficerPatrolRoute
  OfficerScheduleRoute: typeof OfficerScheduleRoute
  OfficerSosRoute: typeof OfficerSosRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerIncidentIdRoute: typeof OfficerIncidentIdRoute
  OfficerIncidentNewRoute: typeof OfficerIncidentNewRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerDispatchRoute: OfficerDispatchRoute,
  OfficerHomeRoute: OfficerHomeRoute,
  OfficerNavigationRoute: OfficerNavigationRoute,
  OfficerNotificationsRoute: OfficerNotificationsRoute,
  OfficerPatrolRoute: OfficerPatrolRoute,
  OfficerScheduleRoute: OfficerScheduleRoute,
  OfficerSosRoute: OfficerSosRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerIncidentIdRoute: OfficerIncidentIdRoute,
  OfficerIncidentNewRoute: OfficerIncidentNewRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OfficerRoute: OfficerRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
