/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPatrolsRouteImport } from './routes/app.patrols'
import { Route as AppOrgRouteImport } from './routes/app.org'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppLocationsRouteImport } from './routes/app.locations'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppUsersIdRouteImport } from './routes/app.users.$id'
import { Route as AppPatrolsIdRouteImport } from './routes/app.patrols.$id'
import { Route as AppIncidentsIdRouteImport } from './routes/app.incidents.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPatrolsRoute = AppPatrolsRouteImport.update({
  id: '/patrols',
  path: '/patrols',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppPatrolsIdRoute = AppPatrolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPatrolsRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/incidents': typeof AppIncidentsRouteWithChildren
  '/app/locations': typeof AppLocationsRoute
  '/app/map': typeof AppMapRoute
  '/app/org': typeof AppOrgRoute
  '/app/patrols': typeof AppPatrolsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/patrols/$id': typeof AppPatrolsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/incidents': typeof AppIncidentsRouteWithChildren
  '/app/locations': typeof AppLocationsRoute
  '/app/map': typeof AppMapRoute
  '/app/org': typeof AppOrgRoute
  '/app/patrols': typeof AppPatrolsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/patrols/$id': typeof AppPatrolsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/incidents': typeof AppIncidentsRouteWithChildren
  '/app/locations': typeof AppLocationsRoute
  '/app/map': typeof AppMapRoute
  '/app/org': typeof AppOrgRoute
  '/app/patrols': typeof AppPatrolsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/incidents/$id': typeof AppIncidentsIdRoute
  '/app/patrols/$id': typeof AppPatrolsIdRoute
  '/app/users/$id': typeof AppUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/alerts'
    | '/app/audit'
    | '/app/incidents'
    | '/app/locations'
    | '/app/map'
    | '/app/org'
    | '/app/patrols'
    | '/app/reports'
    | '/app/users'
    | '/app/'
    | '/app/incidents/$id'
    | '/app/patrols/$id'
    | '/app/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/alerts'
    | '/app/audit'
    | '/app/incidents'
    | '/app/locations'
    | '/app/map'
    | '/app/org'
    | '/app/patrols'
    | '/app/reports'
    | '/app/users'
    | '/app'
    | '/app/incidents/$id'
    | '/app/patrols/$id'
    | '/app/users/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/app/alerts'
    | '/app/audit'
    | '/app/incidents'
    | '/app/locations'
    | '/app/map'
    | '/app/org'
    | '/app/patrols'
    | '/app/reports'
    | '/app/users'
    | '/app/'
    | '/app/incidents/$id'
    | '/app/patrols/$id'
    | '/app/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patrols': {
      id: '/app/patrols'
      path: '/patrols'
      fullPath: '/app/patrols'
      preLoaderRoute: typeof AppPatrolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org': {
      id: '/app/org'
      path: '/org'
      fullPath: '/app/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations': {
      id: '/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/$id': {
      id: '/app/users/$id'
      path: '/$id'
      fullPath: '/app/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/patrols/$id': {
      id: '/app/patrols/$id'
      path: '/$id'
      fullPath: '/app/patrols/$id'
      preLoaderRoute: typeof AppPatrolsIdRouteImport
      parentRoute: typeof AppPatrolsRoute
    }
    '/app/incidents/$id': {
      id: '/app/incidents/$id'
      path: '/$id'
      fullPath: '/app/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
  }
}

interface AppIncidentsRouteChildren {
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIdRoute: AppIncidentsIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppPatrolsRouteChildren {
  AppPatrolsIdRoute: typeof AppPatrolsIdRoute
}

const AppPatrolsRouteChildren: AppPatrolsRouteChildren = {
  AppPatrolsIdRoute: AppPatrolsIdRoute,
}

const AppPatrolsRouteWithChildren = AppPatrolsRoute._addFileChildren(
  AppPatrolsRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersIdRoute: typeof AppUsersIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersIdRoute: AppUsersIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppLocationsRoute: typeof AppLocationsRoute
  AppMapRoute: typeof AppMapRoute
  AppOrgRoute: typeof AppOrgRoute
  AppPatrolsRoute: typeof AppPatrolsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAuditRoute: AppAuditRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppLocationsRoute: AppLocationsRoute,
  AppMapRoute: AppMapRoute,
  AppOrgRoute: AppOrgRoute,
  AppPatrolsRoute: AppPatrolsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
